// File: tools/FieldOps.RepositoryChecks/Program.cs
// Purpose: Generate exact C# declaration locations and enforce repository/documentation policies.
// Symbols and line locations: see docs/code-index.md.
// Important variables: root is the repository boundary; sourceRoots constrain every scan.

using System.Text;
using System.Text.RegularExpressions;

var root = FindRepositoryRoot(AppContext.BaseDirectory);
var command = args.FirstOrDefault() ?? "validate";
return command switch
{
    "index" => WriteIndex(root, checkOnly: false),
    "index-check" => WriteIndex(root, checkOnly: true),
    "validate" => ValidateRepository(root),
    _ => Fail($"Unknown repository-check command: {command}"),
};

/// <summary>Find the first ancestor containing the central build properties.</summary>
static string FindRepositoryRoot(string start)
{
    var directory = new DirectoryInfo(start);
    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "Directory.Build.props")))
        {
            return directory.FullName;
        }

        directory = directory.Parent;
    }

    throw new DirectoryNotFoundException("Repository root was not found.");
}

/// <summary>Generate or compare a deterministic Markdown index of C# declarations.</summary>
static int WriteIndex(string root, bool checkOnly)
{
    var declarations = new List<(string Path, int Line, string Kind, string Name)>();
    var declarationPattern = new Regex(
        @"^\s*(?:public|internal|private|protected)?\s*(?:sealed|static|partial|abstract|readonly)?\s*(class|record|interface|enum|struct)\s+([A-Za-z_][A-Za-z0-9_]*)",
        RegexOptions.CultureInvariant);
    var methodPattern = new Regex(
        @"^\s*(?:public|internal|private|protected)\s+(?:static\s+|async\s+|override\s+|virtual\s+|sealed\s+|partial\s+)*(?:[A-Za-z_][A-Za-z0-9_<>?,.\[\]\s]*\s+)([A-Za-z_][A-Za-z0-9_]*)\s*\(",
        RegexOptions.CultureInvariant);

    foreach (var file in EnumerateAuthoredFiles(root, "*.cs"))
    {
        var relative = Normalize(Path.GetRelativePath(root, file));
        var lines = File.ReadAllLines(file);
        for (var index = 0; index < lines.Length; index++)
        {
            var declaration = declarationPattern.Match(lines[index]);
            if (declaration.Success)
            {
                declarations.Add((relative, index + 1, declaration.Groups[1].Value, declaration.Groups[2].Value));
                continue;
            }

            var method = methodPattern.Match(lines[index]);
            if (method.Success && !string.Equals(method.Groups[1].Value, "if", StringComparison.Ordinal))
            {
                declarations.Add((relative, index + 1, "method", method.Groups[1].Value));
            }
        }
    }

    var output = new StringBuilder()
        .AppendLine("# Generated code index")
        .AppendLine()
        .AppendLine("Generated by `dotnet run --project tools/FieldOps.RepositoryChecks -- index`. Do not edit by hand.")
        .AppendLine()
        .AppendLine("| File | Line | Kind | Symbol |")
        .AppendLine("| --- | ---: | --- | --- |");
    foreach (var item in declarations.OrderBy(item => item.Path, StringComparer.Ordinal).ThenBy(item => item.Line))
    {
        output.Append("| `").Append(item.Path).Append("` | ")
            .Append(item.Line).Append(" | ").Append(item.Kind).Append(" | `")
            .Append(item.Name).AppendLine("` |");
    }

    var path = Path.Combine(root, "docs", "code-index.md");
    var content = output.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    if (checkOnly)
    {
        if (!File.Exists(path) || File.ReadAllText(path).Replace("\r\n", "\n", StringComparison.Ordinal) != content)
        {
            return Fail("docs/code-index.md is stale; regenerate it with the index command.");
        }

        Console.WriteLine("Code index is current.");
        return 0;
    }

    Directory.CreateDirectory(Path.GetDirectoryName(path)!);
    File.WriteAllText(path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    Console.WriteLine("Generated docs/code-index.md.");
    return 0;
}

/// <summary>Validate required docs, source headers, links, content policy, and pinned actions.</summary>
static int ValidateRepository(string root)
{
    var errors = new List<string>();
    string[] requiredFiles =
    [
        "README.md",
        "CHANGELOG.md",
        "CONTRIBUTING.md",
        "SECURITY.md",
        "LICENSE",
        "docs/architecture.md",
        "docs/testing.md",
        "docs/security.md",
        "docs/operations.md",
        "docs/limitations.md",
        "docs/code-index.md",
        "docs/reports/validation.md",
        "docs/reports/generated/validation.json",
    ];
    errors.AddRange(
        requiredFiles.Where(file => !File.Exists(Path.Combine(root, file)))
            .Select(file => $"Missing required file: {file}"));

    foreach (var file in EnumerateAuthoredFiles(root, "*.cs").Concat(EnumerateAuthoredFiles(root, "*.sql")))
    {
        var firstLines = string.Join('\n', File.ReadLines(file).Take(5));
        if (!firstLines.Contains("File:", StringComparison.Ordinal))
        {
            errors.Add($"Missing source header: {Normalize(Path.GetRelativePath(root, file))}");
        }

        if (File.ReadLines(file).Count() > 800)
        {
            errors.Add($"Source file exceeds 800 lines: {Normalize(Path.GetRelativePath(root, file))}");
        }
    }

    var forbidden = new Regex(@"opto[ -]?22", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    var secret = new Regex(
        @"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|gh[pousr]_[A-Za-z0-9]{20,}",
        RegexOptions.CultureInvariant);
    foreach (var file in EnumerateTextFiles(root))
    {
        var content = File.ReadAllText(file);
        if (forbidden.IsMatch(content))
        {
            errors.Add($"Forbidden reference: {Normalize(Path.GetRelativePath(root, file))}");
        }

        if (secret.IsMatch(content))
        {
            errors.Add($"Potential secret: {Normalize(Path.GetRelativePath(root, file))}");
        }
    }

    var markdownLink = new Regex(@"\[[^\]]*\]\(([^)]+)\)", RegexOptions.CultureInvariant);
    foreach (var file in EnumerateAuthoredFiles(root, "*.md"))
    {
        foreach (Match match in markdownLink.Matches(File.ReadAllText(file)))
        {
            var target = match.Groups[1].Value.Split('#')[0].Trim('<', '>');
            if (target.Length == 0 || Uri.TryCreate(target, UriKind.Absolute, out _))
            {
                continue;
            }

            var resolved = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(file)!, target));
            if (!File.Exists(resolved) && !Directory.Exists(resolved))
            {
                errors.Add($"Broken link in {Normalize(Path.GetRelativePath(root, file))}: {target}");
            }
        }
    }

    var actionPattern = new Regex(@"uses:\s*[^@\s]+@([^\s#]+)", RegexOptions.CultureInvariant);
    foreach (var file in Directory.EnumerateFiles(Path.Combine(root, ".github", "workflows"), "*.yml"))
    {
        foreach (Match match in actionPattern.Matches(File.ReadAllText(file)))
        {
            if (!Regex.IsMatch(match.Groups[1].Value, "^[a-f0-9]{40}$", RegexOptions.CultureInvariant))
            {
                errors.Add($"Action is not pinned to a full SHA: {match.Value}");
            }
        }
    }

    if (errors.Count > 0)
    {
        foreach (var error in errors)
        {
            Console.Error.WriteLine(error);
        }

        return 1;
    }

    Console.WriteLine("Repository structure, links, headers, content, and action pins are valid.");
    return 0;
}

static IEnumerable<string> EnumerateAuthoredFiles(string root, string pattern) =>
    new[] { "src", "tests", "tools" }
        .SelectMany(directory => Directory.EnumerateFiles(Path.Combine(root, directory), pattern, SearchOption.AllDirectories))
        .Where(path => !IsGenerated(path));

static IEnumerable<string> EnumerateTextFiles(string root) =>
    Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories)
        .Where(path => new[] { ".cs", ".csproj", ".json", ".md", ".props", ".sql", ".xaml", ".xml", ".yml", ".yaml" }.Contains(Path.GetExtension(path), StringComparer.OrdinalIgnoreCase))
        .Where(path => !IsGenerated(path));

static bool IsGenerated(string path) =>
    path.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", StringComparison.Ordinal)
    || path.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.Ordinal)
    || path.Contains($"{Path.DirectorySeparatorChar}.packages{Path.DirectorySeparatorChar}", StringComparison.Ordinal)
    || path.Contains($"{Path.DirectorySeparatorChar}artifacts{Path.DirectorySeparatorChar}", StringComparison.Ordinal);

static string Normalize(string path) => path.Replace('\\', '/');

static int Fail(string message)
{
    Console.Error.WriteLine(message);
    return 1;
}
